# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 16:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20160117_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 21, 16, 7, 54, 419585, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='honoured_guest',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 21, 16, 8, 1, 576880, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiletoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 21, 16, 8, 7, 901951, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiletoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 21, 16, 8, 10, 593556, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
