# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 18:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionTradition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('link', models.URLField(blank=True, null=True)),
                ('year_established', models.PositiveSmallIntegerField()),
                ('genres', models.ManyToManyField(to='tags.Genre')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConventionTraditionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='convents.ConventionTradition')),
            ],
            options={
                'managed': True,
                'abstract': False,
                'db_table': 'convents_conventiontradition_translation',
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='conventiontraditiontranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
